### ISSUE TITLE
Local german small fix: Application-Yaga/locale/de-DE/definitions.php

### ISSUE THREAD

**Issue by phreak** [hgtonight/Application-Yaga#108]
$Definition['Yaga.Badge.Earned'] = 'Du hast diese Auszeichnung erhalten';

If this is only shown on the Badge Detail Padge than it is missing an "am".

$Definition['Yaga.Badge.Earned'] = 'Du hast diese Auszeichnung erhalten am';

Because it's follow by a date (date of receiving the badge).

**Comment by bleistivt** [comment]
I agree, that would be a better translation.

I think I originally wrote it like that because I had timeago installed in my forum, which displays fuzzy timestamps like: `vor 8 Monaten`

Btw., you can submit pull request for changes in your browser:
https://github.com/hgtonight/Application-Yaga/blob/master/locale/de-DE/definitions.php
Just click the pencil symbol.
